### ISSUE TITLE
Instructions for installing from source?

### ISSUE THREAD

**Issue by inorton** [zero9178/C-Cpp-Coverage-for-CLion#3]
I'd like to try and get this working and contribute myself. Are there instructions for installing this from github rather than the clion plugins window?

**Comment by zero9178** [comment]
Installation instruction should be very simple. You can either use Intellij Idea Ultimate if you have a license or use intellij community edition which you can get for free here https://www.jetbrains.com/idea/download

When installing make sure to have VCS plugins enabled and then you should be able to import the repository from git. To compile you'll need to add CLion Platform Plugin SDK. Follow this guide here and just specify the CLion path instead of the Intellij one they use https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html. To run and debug you'll want to create a run and debug configuration for CLion which you can find more about here. https://www.jetbrains.com/help/idea/run-debug-configuration-plugin.html. Here you need to set CLion as JRE. This will start a CLion instance in a sandbox enviroment. 

Think that should be all
